all:				 Upper.class UpperClientThread.class Peer.class UpperServerThread

	

UpperServerThread.class:	UpperServerThread.java
				@javac UpperServerThread.java
				
UpperClientThread.class:	UpperClientThread.java
				@javac UpperClientThread.java

Upper.class:		Upper.java
				@javac Upper.java
				
Peer.class:		Peer.java
				@javac Peer.java

clean:
				@rm -rf *.class *~

info:
				@echo "Origem:"
				@echo "   Roland Teodorowitsch"
				@echo "   29 maio 2009"
